INSERT INTO products (id, name, in_stock, price) VALUES (1, 'Bolsa de tela reutilizable', 1, '2.50');
INSERT INTO products (id, name, in_stock, price) VALUES (2, 'Mochila tipo saco', 0, '3.90');
INSERT INTO products (id, name, in_stock, price) VALUES (3, 'Bolígrafo personalizado', 1, '0.75');
INSERT INTO products (id, name, in_stock, price) VALUES (4, 'Libreta pequeña', 1, '1.80');
INSERT INTO products (id, name, in_stock, price) VALUES (5, 'Botella reutilizable', 1, '4.50');
INSERT INTO products (id, name, in_stock, price) VALUES (6, 'Taza personalizada', 1, '3.50');
INSERT INTO products (id, name, in_stock, price) VALUES (7, 'Caramelos o chocolatinas', 0, '1.20');
INSERT INTO products (id, name, in_stock, price) VALUES (8, 'Llavero', 1, '1.00');
INSERT INTO products (id, name, in_stock, price) VALUES (9, 'Velas aromáticas', 1, '2.80');
INSERT INTO products (id, name, in_stock, price) VALUES (10, 'Neceser', 1, '3.20');
INSERT INTO products (id, name, in_stock, price) VALUES (11, 'Tote bag premium', 1, '4.20');
INSERT INTO products (id, name, in_stock, price) VALUES (12, 'Abanico', 0, '2.00');
INSERT INTO products (id, name, in_stock, price) VALUES (13, 'Calcetines personalizados', 1, '4.80');
INSERT INTO products (id, name, in_stock, price) VALUES (14, 'Jabón artesanal', 1, '2.50');
INSERT INTO products (id, name, in_stock, price) VALUES (15, 'Bálsamo labial', 1, '1.90');
INSERT INTO products (id, name, in_stock, price) VALUES (16, 'Espejo de bolsillo', 1, '1.70');
INSERT INTO products (id, name, in_stock, price) VALUES (17, 'Auriculares básicos', 1, '5.90');
INSERT INTO products (id, name, in_stock, price) VALUES (18, 'Power bank', 0, '8.50');
INSERT INTO products (id, name, in_stock, price) VALUES (19, 'USB personalizada', 1, '4.00');
INSERT INTO products (id, name, in_stock, price) VALUES (20, 'Agenda o planner', 1, '5.50');
INSERT INTO products (id, name, in_stock, price) VALUES (21, 'Posavasos', 1, '1.50');
INSERT INTO products (id, name, in_stock, price) VALUES (22, 'Mini planta o cactus', 1, '3.00');
INSERT INTO products (id, name, in_stock, price) VALUES (23, 'Gafas de sol económicas', 0, '3.80');
INSERT INTO products (id, name, in_stock, price) VALUES (24, 'Pegatinas personalizadas', 1, '0.90');
INSERT INTO products (id, name, in_stock, price) VALUES (25, 'Imán decorativo', 1, '1.10');
INSERT INTO products (id, name, in_stock, price) VALUES (26, 'Tarjeta con mensaje personalizado', 1, '0.60');
INSERT INTO products (id, name, in_stock, price) VALUES (27, 'Paquete de té o café', 1, '2.30');
INSERT INTO products (id, name, in_stock, price) VALUES (28, 'Pulsera o cinta de tela', 1, '1.40');
INSERT INTO products (id, name, in_stock, price) VALUES (29, 'Mini perfume o ambientador', 0, '3.60');
INSERT INTO products (id, name, in_stock, price) VALUES (30, 'Juego de cartas o pasatiempos pequeños', 1, '2.70');

INSERT INTO product_comments (id, product_id, text) VALUES (1, 2, 'Me da pena que la mochila no esté disponible ahora mismo.');
INSERT INTO product_comments (id, product_id, text) VALUES (2, 2, '¿Tenéis previsto reponerla pronto?');
INSERT INTO product_comments (id, product_id, text) VALUES (3, 13, 'Muy cómodos, los volvería a comprar.');
INSERT INTO product_comments (id, product_id, text) VALUES (4, 13, 'El diseño personalizado queda genial.');
INSERT INTO product_comments (id, product_id, text) VALUES (5, 13, 'Buenos para regalo, aunque la talla viene un poco justa.');
INSERT INTO product_comments (id, product_id, text) VALUES (6, 13, 'No están mal, pero el tejido podría ser algo más suave.');
INSERT INTO product_comments (id, product_id, text) VALUES (7, 13, 'Coincido con lo del tejido, aun así son de mis favoritos.');
INSERT INTO product_comments (id, product_id, text) VALUES (8, 13, 'Más baratos que en otras tiendas de merchandising.');
INSERT INTO product_comments (id, product_id, text) VALUES (9, 13, 'A mí el estampado me parece demasiado llamativo.');
INSERT INTO product_comments (id, product_id, text) VALUES (10, 13, 'Bien acabados, aunque un poco caros.');
INSERT INTO product_comments (id, product_id, text) VALUES (11, 9, 'Aromatizan muy bien una habitación pequeña.');
INSERT INTO product_comments (id, product_id, text) VALUES (12, 9, 'El aroma es agradable, pero dura menos de lo que esperaba.');
INSERT INTO product_comments (id, product_id, text) VALUES (13, 14, 'Jabón artesanal muy agradable. Repetiría.');
INSERT INTO product_comments (id, product_id, text) VALUES (14, 14, 'Huele genial y no reseca la piel.');
INSERT INTO product_comments (id, product_id, text) VALUES (15, 14, 'Un poco intenso para mi gusto, pero de buena calidad.');
INSERT INTO product_comments (id, product_id, text) VALUES (16, 14, 'Se nota que no es un jabón industrial cualquiera.');
INSERT INTO product_comments (id, product_id, text) VALUES (17, 16, 'Muy buena relación calidad-precio.');
INSERT INTO product_comments (id, product_id, text) VALUES (18, 24, 'Mis pegatinas favoritas :)');
INSERT INTO product_comments (id, product_id, text) VALUES (19, 30, 'Las cartas son algo rígidas, no lo volvería a comprar.');
INSERT INTO product_comments (id, product_id, text) VALUES (20, 30, 'El juego entretiene, pero coincido en que el material podría ser mejor.');
INSERT INTO product_comments (id, product_id, text) VALUES (21, 30, 'No me convenció. Las instrucciones son poco claras.');

INSERT INTO customers (id, name, email, customer_since) VALUES (1, 'Jaime Pepino', 'jaime.pepino@example.com', '2006-04-02');
INSERT INTO customers (id, name, email, customer_since) VALUES (2, 'Ana Lechuga', 'ana.lechuga@example.com', '2005-01-30');
INSERT INTO customers (id, name, email, customer_since) VALUES (3, 'Boris Tomate', 'boris.tomate@example.com', '2008-12-02');
INSERT INTO customers (id, name, email, customer_since) VALUES (4, 'Shannon Perejil', 'shannon.perejil@example.com', '2009-03-24');
INSERT INTO customers (id, name, email, customer_since) VALUES (5, 'Susana Cheddar', 'susana.cheddar@example.com', '2007-10-01');
INSERT INTO customers (id, name, email, customer_since) VALUES (6, 'Jorge Ajo', 'jorge.ajo@example.com', '2010-05-18');

INSERT INTO orders (id, customer_id, order_date) VALUES (1, 4, '2009-01-12T10:23:00');
INSERT INTO orders (id, customer_id, order_date) VALUES (2, 6, '2010-06-09T21:01:00');
INSERT INTO orders (id, customer_id, order_date) VALUES (3, 1, '2010-07-18T22:32:00');

INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (1, 1, 2, 2, '0.99');
INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (2, 1, 3, 4, '2.50');
INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (3, 1, 4, 1, '15.50');
INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (4, 2, 1, 5, '3.75');
INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (5, 2, 4, 2, '17.99');
INSERT INTO order_lines (id, order_id, product_id, amount, purchase_price) VALUES (6, 3, 1, 8, '5.99');
